# Generated by Django 4.2 on 2023-04-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=2000)),
                ('block', models.BooleanField(default=True)),
                ('user_count', models.IntegerField(max_length=250)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expired_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
