# Generated by Django 4.2 on 2023-04-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblockapp', '0002_alter_user_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_count',
            field=models.IntegerField(null=True),
        ),
    ]
