# Generated by Django 4.2 on 2023-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblockapp', '0003_alter_user_user_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expired_date',
            new_name='expiredAt',
        ),
        migrations.AlterField(
            model_name='user',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
