# Generated by Django 4.2 on 2023-04-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblockapp', '0004_rename_expired_date_user_expiredat_alter_user_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block',
            field=models.BooleanField(default=True),
        ),
    ]
