# Generated by Django 4.2 on 2023-04-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblockapp', '0005_alter_user_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiredAt',
            field=models.DateTimeField(),
        ),
    ]
