# Generated by Django 4.2 on 2023-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblockapp', '0006_alter_user_expiredat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiredAt',
            field=models.DateTimeField(null=True),
        ),
    ]
